import type { ConditionRating } from "@/features/catalog/condition";
import type { Audience } from "@/features/catalog/audiences";
import type { Color } from "@/features/catalog/colors";
import type { GarmentType } from "@/features/catalog/garment-types";
import type { ProductSize } from "@/features/catalog/sizes";
import type { IntakeItemId, IntakeSourceType } from "@/features/intake/server/intake.types";
import type { ProductId, ProductMeasurements, ProductStatus } from "@/features/catalog/server/product.types";
import type { Money } from "@/types/money";

/** Identifies the internal draft used by Product Manager operations. */
export type ProductDraftId = ProductId;

/** Keeps the operational list intentionally small while drafts are the only editable state. */
export type ProductDraftSummary = Readonly<{
  id: ProductDraftId;
  sku: string;
  status: ProductStatus;
  title: string;
  updatedAt: Date;
}>;

/**
 * Represents the combined operational form state without collapsing Intake and
 * Product into one persisted domain entity.
 */
export type ProductDraft = Readonly<{
  acquisitionCost: Money | null;
  audience: Audience | null;
  brand: string | null;
  color: string | null;
  conditionNotes: string | null;
  conditionRating: ConditionRating | null;
  description: string | null;
  garmentType: GarmentType | null;
  id: ProductDraftId;
  intakeItemId: IntakeItemId;
  materialDetails: string | null;
  measurements: ProductMeasurements | null;
  price: Money | null;
  receivedAt: string;
  sizeLabel: ProductSize | null;
  sku: string;
  sourceType: IntakeSourceType;
  status: ProductStatus;
  title: string;
  updatedAt: Date;
}>;

/** Supplies the editable operational facts for an existing draft. */
export type SaveProductDraftInput = Readonly<{
  acquisitionCost: Money | null;
  audience: Audience | null;
  brand: string | null;
  color: Color | null;
  conditionNotes: string | null;
  conditionRating: ConditionRating | null;
  description: string | null;
  garmentType: GarmentType | null;
  id: ProductDraftId;
  materialDetails: string | null;
  measurements: ProductMeasurements | null;
  price: Money | null;
  receivedAt: string;
  sizeLabel: ProductSize | null;
  sourceType: IntakeSourceType;
  title: string;
}>;

/**
 * Supplies all approved Intake and Product facts for the first atomic draft
 * save. Creation and later edits intentionally accept the same facts so the
 * operator does not have to perform a second save to complete a garment.
 */
export type CreateProductDraftInput = Omit<SaveProductDraftInput, "id">;

/** Returns the identifiers generated by the database after an atomic draft creation. */
export type CreatedProductDraft = Readonly<{
  id: ProductDraftId;
  intakeItemId: IntakeItemId;
  sku: string;
}>;
