import Image from "next/image";
import Link from "next/link";

import type { CatalogProductPreview } from "@/types/catalog";

type PaletteName = "a" | "b" | "c";
type Props = Readonly<{ dark: boolean; palette: PaletteName; product: CatalogProductPreview | null }>;

const palettes = {
  a: { name: "A · Azul profundo", light: "bg-[#f8f7f2] text-[#10233d]", dark: "bg-[#0d1b2c] text-[#f3f5f6]", brand: "bg-[#1461a4]", soft: "bg-[#dceef6]", warm: "bg-[#ede0cc]", line: "border-[#9bc3dc]", muted: "text-[#52677c]" },
  b: { name: "B · Océano", light: "bg-[#f5f8f7] text-[#123342]", dark: "bg-[#102b35] text-[#f1f7f6]", brand: "bg-[#16758a]", soft: "bg-[#d9f0f2]", warm: "bg-[#e7dcc9]", line: "border-[#8ec8d1]", muted: "text-[#4d6b74]" },
  c: { name: "C · Tinta y celeste", light: "bg-[#faf8f3] text-[#101d38]", dark: "bg-[#11182c] text-[#f4f5f9]", brand: "bg-[#2456b6]", soft: "bg-[#dce8ff]", warm: "bg-[#f0e1ca]", line: "border-[#a8bee9]", muted: "text-[#53617b]" },
} as const;

function BlueProduct({ priority = false, product }: Readonly<{ priority?: boolean; product: CatalogProductPreview | null }>) {
  if (!product) return <p className="text-sm opacity-75">La composición se adapta cuando no hay productos recomendados.</p>;
  const image = product.image;
  return <article className="group max-w-sm"><Link aria-label={`Ver ${product.name}`} href={product.href}>{"width" in image ? <Image alt={image.alt} className="aspect-[4/5] w-full object-cover" height={image.height} priority={priority} src={image.src} width={image.width} /> : <Image alt={image.alt} className="aspect-[4/5] w-full object-cover" priority={priority} src={image.src} />}<div className="pt-3"><h2 className="font-serif text-xl leading-tight">{product.name}</h2>{product.price ? <p className="mt-1 text-sm font-medium">{product.price}</p> : null}</div></Link></article>;
}

/** Isolated warm-editorial composition tuned around REVA-blue semantic palette candidates. */
export function RevaBlueEditorialPlayground({ dark, palette: paletteName, product }: Props) {
  const palette = palettes[paletteName]; const background = dark ? palette.dark : palette.light; const inverse = dark ? "bg-[#f3f5f6] text-[#10233d]" : "bg-[#10233d] text-white"; const muted = dark ? "text-[#c6d1da]" : palette.muted; const border = dark ? "border-[#496375]" : palette.line;
  const paletteHref = (name: PaletteName) => `/playground/reva-blue/${name}${dark ? "?tema=oscuro" : ""}`;
  const themeHref = `/playground/reva-blue/${paletteName}${dark ? "" : "?tema=oscuro"}`;
  return <main className={`min-h-screen ${background}`}><header className={`mx-auto flex max-w-7xl items-center justify-between gap-4 border-b ${border} px-4 py-4 sm:px-8`}><Link aria-label="REVA Playground" className="font-serif text-xl tracking-[0.24em]" href="/playground">REVA</Link><nav aria-label="Navegación experimental" className="hidden items-center gap-6 text-sm font-medium lg:flex"><Link href="/catalogo">Catálogo</Link><Link href="/como-funciona">Cómo funciona</Link><Link href="/vender">Vender</Link><Link href="/donar">Donar</Link></nav><div className="flex items-center gap-3"><Link className="hidden text-sm font-medium sm:block" href="/iniciar-sesion">Ingresar</Link><Link aria-label={dark ? "Ver modo claro" : "Ver modo oscuro"} className={`rounded-full border ${border} px-3 py-2 text-xs font-medium`} href={themeHref}>{dark ? "Claro" : "Oscuro"}</Link></div></header>
    <section className="mx-auto grid max-w-7xl gap-10 px-4 pb-14 pt-12 sm:px-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-end lg:pt-20"><div className="max-w-xl space-y-7 lg:pb-12"><p className={`text-xs font-semibold uppercase tracking-[0.18em] ${dark ? "text-[#9ed6eb]" : "text-[#1461a4]"}`}>Moda circular en Guatemala</p><h1 className="font-serif text-5xl leading-[0.9] tracking-tight sm:text-7xl">Prendas con historia. Estilo con futuro.</h1><p className={`max-w-md text-base leading-7 ${muted}`}>Descubre piezas seleccionadas para seguir circulando con intención.</p><div className="flex flex-wrap gap-3"><Link className={`rounded-full px-5 py-3 text-sm font-semibold text-white ${palette.brand}`} href="/catalogo">Explorar prendas</Link><Link className={`rounded-full border ${border} px-5 py-3 text-sm font-semibold`} href="/vender">Quiero vender</Link></div></div><div className="relative mx-auto w-full max-w-md lg:max-w-none"><div className={`absolute -left-7 top-10 h-44 w-44 rounded-full ${palette.warm} opacity-80`} /><BlueProduct priority product={product} /></div></section>
    <section className={`${palette.soft} py-9`}><div className="mx-auto grid max-w-7xl gap-6 px-4 sm:px-8 lg:grid-cols-[0.45fr_1fr] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.18em]">Recomendado por REVA</p><h2 className="mt-2 font-serif text-3xl leading-tight">Descubre primero.</h2></div><div className="grid gap-5 sm:grid-cols-[0.55fr_1fr] sm:items-end"><BlueProduct product={product} /><div className="space-y-3"><p className="max-w-sm text-sm leading-6">Una selección breve; la fotografía y la pieza son la prioridad.</p><Link className="text-sm font-semibold underline underline-offset-8" href="/catalogo">Ver catálogo</Link></div></div></div></section>
    <section className="mx-auto grid max-w-7xl gap-6 px-4 py-14 sm:px-8 sm:py-20 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><div><p className={`text-xs font-semibold uppercase tracking-[0.18em] ${dark ? "text-[#9ed6eb]" : "text-[#1461a4]"}`}>¿Tienes prendas que ya no usas?</p><h2 className="mt-3 max-w-md font-serif text-4xl leading-tight">Elige cómo quieres que sigan circulando.</h2></div><div className="flex flex-wrap gap-3 lg:justify-self-end"><Link className={`rounded-full px-5 py-3 text-sm font-semibold ${inverse}`} href="/vender">Vender</Link><Link className={`rounded-full border ${border} px-5 py-3 text-sm font-semibold`} href="/donar">Donar</Link></div></section>
    <section className={`${palette.warm} py-12`}><div className="mx-auto max-w-7xl px-4 sm:px-8"><p className="max-w-2xl font-serif text-3xl leading-tight">Moda circular clara, cuidada y cercana.</p><Link className="mt-5 inline-block text-sm font-semibold underline underline-offset-8" href="/como-funciona">Cómo funciona REVA</Link></div></section>
    <footer className={`border-t ${border} px-4 py-8 sm:px-8`}><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 text-sm"><p className="font-serif tracking-[0.18em]">REVA</p><div className="flex gap-4"><Link href="/catalogo">Catálogo</Link><Link href="/como-funciona">Cómo funciona</Link><Link href="/contacto">Contacto</Link></div><nav aria-label="Paletas experimentales" className="flex gap-2">{(["a", "b", "c"] as const).map((name) => <Link aria-current={paletteName === name ? "page" : undefined} className={`rounded-full border ${border} px-3 py-1 text-xs`} href={paletteHref(name)} key={name}>{name.toUpperCase()}</Link>)}</nav></div></footer>
  </main>;
}
